# Lab 09
## Complete the questions below in the space provided.

Before starting, download the file exam.csv.  This file is a comma delimited file that stores the city codes and the number of English, French and German exams that will be held in the corresponding cities.

Import numpy package in your code as np

In [1]:
import numpy as np

Read the data in the comma-delimited file, exam.csv into a numpy array, data as integers and print it.

In [2]:
data = np.loadtxt('exam.csv', skiprows = 1, dtype = 'int', delimiter = ',')
print( data)

[[  1 125  75  37]
 [  6 325 350 150]
 [  7 104  45  42]
 [  9 132 145 153]
 [ 16 112  67  86]
 [ 26 400 205  34]
 [ 34 465 154 501]
 [ 35 356 143 113]
 [ 42 219  25  63]
 [ 45  86  34  78]
 [ 61 348  19  13]]


Separate city codes and exam information into city and exams arrays and print them

In [3]:
city, exams = np.hsplit(data, [1])
print(city)
print(exams)

[[ 1]
 [ 6]
 [ 7]
 [ 9]
 [16]
 [26]
 [34]
 [35]
 [42]
 [45]
 [61]]
[[125  75  37]
 [325 350 150]
 [104  45  42]
 [132 145 153]
 [112  67  86]
 [400 205  34]
 [465 154 501]
 [356 143 113]
 [219  25  63]
 [ 86  34  78]
 [348  19  13]]


Store the total number of candidates who will enter in each city in total array and print it

In [5]:
total = np.sum(exams, axis = 1)
print(total)

[ 237  825  191  430  265  639 1120  612  307  198  380]


Find the index ind of the maximum total and print it.

In [6]:
ind = np.argmax(total)
print(ind)

6


Find the city code code with highest number of total candidates and print it

In [7]:
code = city[ind]
print(code)

[34]


In [ ]:
Create an array query of those exam values with English exam more than the sum of French and German Exams and print query array.

In [8]:
query = exams[exams[:,0] > exams[:,1] + exams[:,2]]
print(query)

[[125  75  37]
 [104  45  42]
 [400 205  34]
 [356 143 113]
 [219  25  63]
 [348  19  13]]


In [ ]:
Create an array pos to store the indexes of those cities in exams array where either French exam candidates or German exam 
candidates are more than English exam candidates and print pos.


In [9]:
pos = np.where((exams[:,1] > exams[:,0]) | (exams[:,2] > exams[:,0]))
print(pos)

(array([1, 3, 6], dtype=int64),)


Add 10 more candiates to English and German exam candidates in exams array and after merging city codes with exams array write the data to a new file newdata.txt.


In [10]:
exams[:,0:3:2] += 10
merged = np.hstack([city,exams])
np.savetxt('newdata.txt', merged, fmt = '%s')